### ISSUE TITLE
correct work in blender 3.0

### ISSUE THREAD

**Issue by ArtemSh-Hd** [marcopavanello/pbr-materials#6]
Hello.
Complex materials and textures do not work in blender 3.0.0b
Simple materials may also need improvement or optimization. Since the set of distribution parameters and subsurface methods has changed.
Thanks for your work.

**Comment by marcopavanello** [comment]
The add-on is discontinued, it doesn't make sense anymore to support it because now there is the Assets Browser in Blender 3.0
