### ISSUE TITLE
PBR MATERIALS ADDON BUG IN BLENDER 3.0 

### ISSUE THREAD

**Issue by filipemoretzsohn** [marcopavanello/pbr-materials#8]
Unfortunately, some materials does not work in BLENDER 3.0 (Glass / Atmosphere...), work perfectly in BLENDER 3.93.6. Please, fix it for 3.0!! PBR MATERIALS ADDON are great and fast to use. Tks a lot.

**Comment by marcopavanello** [comment]
The add-on is discontinued, it doesn't make sense anymore to support it because now there is the Assets Browser in Blender 3.0

**Comment by filipemoretzsohn** [comment]
Tks a lot Marco for your return. Again, tks for the tip about asset browser in Bender 3.0. Bye. Filipe
